server:
  port: ${PORT:8080}
  servlet:
    context-path: /finito/api

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  resend:
    api-key: ${re_RdEydRwN_J13RjA4ZLoJfjzugGtpp2k5Y}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: lancamento
        dialect: org.hibernate.dialect.PostgreSQLDialect