server:
  port: ${PORT:8080}
  servlet:
    context-path: /finito/api

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:joanreis.dev@gmail.com}
    password: ${MAIL_PASSWORD:xamm vgbn yxfs blgr}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: lancamento
        dialect: org.hibernate.dialect.PostgreSQLDialect